-- Consultados dados

--todas as colunas

SELECT * FROM [TABELA DE PRODUTOS];
SELECT * FROM [TABELA DE CLIENTES];

--colunas específicas

SELECT [NOME],[CIDADE] FROM [TABELA DE CLIENTES];
SELECT [CIDADE], [NOME] FROM [TABELA DE CLIENTES];

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]
FROM [TABELA DE PRODUTOS];

--apelidando colunas

SELECT [NOME] AS [NOME DO CLIENTE], [CPF], [ESTADO], [CIDADE]
FROM [TABELA DE CLIENTES] 


SELECT [NOME] AS [NOME DO CLIENTE], [CPF] AS [IDENTIFICADOR],  [ESTADO], [CIDADE]
FROM [TABELA DE CLIENTES] 

--removendo duplicadas

/*SELECT [SABOR] FROM [TABELA DE PRODUTOS];*/

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];

